services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3003:3003"

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

volumes:
  postgres_data: