name: Checks
on:
  push:
    branches:
      - master

jobs:
  test-lints:
    name: Test Lints
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Docker Version
        run: docker --version

      - name: Lint
        run: docker compose run --rm app sh -c "npm run lint"

      - name: Build Docker Image
        run: docker build -t suyeshlawand/interview-nest:latest .
      
      - name: Push Docker Image
        run: docker push suyeshlawand/interview-nest:latest
